// Code generated by BobGen sqlite v0.15.5. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker"
	"github.com/stephenafamo/bob"
	models "go.bbkane.com/taggedmarks2/bob/models"
)

type MigrationMod interface {
	Apply(*MigrationTemplate)
}

type MigrationModFunc func(*MigrationTemplate)

func (f MigrationModFunc) Apply(n *MigrationTemplate) {
	f(n)
}

type MigrationModSlice []MigrationMod

func (mods MigrationModSlice) Apply(n *MigrationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// MigrationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MigrationTemplate struct {
	Name func() string

	f *factory
}

// Apply mods to the MigrationTemplate
func (o *MigrationTemplate) Apply(mods ...MigrationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Migration
// this does nothing with the relationship templates
func (o MigrationTemplate) toModel() *models.Migration {
	m := &models.Migration{}

	if o.Name != nil {
		m.Name = o.Name()
	}

	return m
}

// toModels returns an models.MigrationSlice
// this does nothing with the relationship templates
func (o MigrationTemplate) toModels(number int) models.MigrationSlice {
	m := make(models.MigrationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Migration
// according to the relationships in the template. Nothing is inserted into the db
func (t MigrationTemplate) setModelRels(o *models.Migration) {}

// BuildSetter returns an *models.MigrationSetter
// this does nothing with the relationship templates
func (o MigrationTemplate) BuildSetter() *models.MigrationSetter {
	m := &models.MigrationSetter{}

	if o.Name != nil {
		m.Name = omit.From(o.Name())
	}

	return m
}

// BuildManySetter returns an []*models.MigrationSetter
// this does nothing with the relationship templates
func (o MigrationTemplate) BuildManySetter(number int) []*models.MigrationSetter {
	m := make([]*models.MigrationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Migration
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationTemplate.Create
func (o MigrationTemplate) Build() *models.Migration {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MigrationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationTemplate.CreateMany
func (o MigrationTemplate) BuildMany(number int) models.MigrationSlice {
	m := make(models.MigrationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMigration(m *models.MigrationSetter) {
	if m.Name.IsUnset() {
		m.Name = omit.From(random[string](nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Migration
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MigrationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Migration) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a migration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MigrationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Migration, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// create builds a migration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *MigrationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.Migration, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMigration(opt)

	m, err := models.MigrationsTable.Insert(ctx, exec, opt)
	if err != nil {
		return ctx, nil, err
	}
	ctx = migrationCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple migrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MigrationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MigrationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// createMany builds multiple migrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o MigrationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.MigrationSlice, error) {
	var err error
	m := make(models.MigrationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// Migration has methods that act as mods for the MigrationTemplate
var MigrationMods migrationMods

type migrationMods struct{}

func (m migrationMods) RandomizeAllColumns(f *faker.Faker) MigrationMod {
	return MigrationModSlice{
		MigrationMods.RandomName(f),
	}
}

// Set the model columns to this value
func (m migrationMods) Name(val string) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m migrationMods) NameFunc(f func() string) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m migrationMods) UnsetName() MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationMods) RandomName(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.Name = func() string {
			return random[string](f)
		}
	})
}

func (m migrationMods) ensureName(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		if o.Name != nil {
			return
		}

		o.Name = func() string {
			return random[string](f)
		}
	})
}
